// Contract fixtures used only by tests, never imported by runtime views/services.
import type { RentalApiDetail, RentalApiPage } from "../src/types/rentalApi"
import type { RenewalApiRecord, RenewalApiQuote } from "../src/types/renewalApi"
import type { ApiActor } from "../src/services/authApi"
export const rental: RentalApiDetail = {
  id: "r1",
  customer: { id: "c1", fullName: "Customer" },
  facility: { id: "f1", code: "F1", name: "Cơ sở 1" },
  storageUnit: { id: "u1", code: "A-01" },
  unitType: { id: "t1", code: "SMALL", name: "Small Storage" },
  status: "active",
  startDate: "2026-10-01",
  contractEndDate: "2026-10-31",
  monthlyPrice: 5500000,
  currency: "VND",
  dataWarnings: [],
  reservationId: "b1",
  actualReturnedAt: null,
  completedAt: null,
  financialSummary: {
    completeness: "UNKNOWN",
    currency: "VND",
    outstandingAmount: null,
    overdueAmount: null,
    nextDueDate: null,
    reason: "Source missing",
  },
  access: { completeness: "UNKNOWN", status: null, reason: "Source missing" },
}
export const renewal: RenewalApiRecord = {
  id: "n1",
  rentalId: "r1",
  customer: rental.customer,
  facility: rental.facility,
  storageUnit: rental.storageUnit,
  status: "pending",
  reviewState: "READY",
  oldEndDate: "2026-10-31",
  newEndDate: "2027-01-31",
  amount: 16000000,
  currency: "VND",
  createdAt: "2026-10-06T00:00:00Z",
  version: 2,
  requestedBy: "c1",
  acceptedQuoteId: "q1",
  acceptedRevision: 1,
  reviewerId: null,
  reviewedAt: null,
  reviewReason: null,
  approvedPaymentDeadline: null,
  extensionHoldRef: null,
  financialCheck: {
    completeness: "UNKNOWN",
    checkedAt: null,
    blockingObligationRefs: null,
    hasUnresolvedDispute: null,
  },
  allowedActions: ["REJECT", "CANCEL", "ACCEPT_REVISED_QUOTE"],
  disabledReasons: ["DEFERRED_SOURCE: financial"],
}
export const quote: RenewalApiQuote = {
  id: "q1",
  rentalId: "r1",
  customerId: "c1",
  quotedAt: "2026-10-06T00:00:00Z",
  expiresAt: "2026-10-06T00:10:00Z",
  oldEndDate: "2026-10-31",
  extensionStartDate: "2026-11-01",
  extensionEndExclusive: "2027-02-01",
  newEndDate: "2027-01-31",
  unitTypeId: "t1",
  storageUnitId: "u1",
  facilityId: "f1",
  pricingPackageCode: "P3",
  packagePolicyRef: "p1",
  packagePolicyVersion: "v1",
  rentalMonths: 3,
  monthlyPrice: 5500000,
  discountRate: 0.03,
  subtotal: 16500000,
  discountAmount: 495000,
  totalAfterDiscount: 16005000,
  renewalDepositAmount: 3201000,
  remainingRentalAmount: 12804000,
  currency: "VND",
  renewalPolicyRef: "policy1",
  renewalPolicyVersion: "v1",
}
export function page<T>(data: T[]): RentalApiPage<T> {
  return {
    data,
    pagination: {
      page: 0,
      pageSize: 20,
      totalItems: data.length,
      totalPages: data.length ? 1 : 0,
      sort: "createdAt: DESC",
    },
    correlationId: "trace1",
  }
}
export const manager: ApiActor = {
  id: "m1",
  email: "m@example.test",
  fullName: "Manager",
  phone: null,
  permanentAddress: null,
  emergencyContactName: null,
  emergencyContactPhone: null,
  avatarUrl: null,
  status: "ACTIVE",
  roles: ["MANAGER"],
  facilityScopes: { f1: "MANAGE" },
  mustChangePassword: false,
  permissions: ["rentals:read", "rentals:update"],
}
