import { useState } from 'react'
import Layout, { getInitialPage, Icon } from '../../components/Layout'
import { Badge, Card, ProgressBar, SectionHeader, StatCard, Table, Tbody, Td, Th, Thead, Tr } from '../../components/ui'
import { useLanguage } from '../../i18n/LanguageContext'
import { useStorageHub } from '../../store/StorageHubContext'
import type { User } from '../../types'
import ProfileView from '../ProfileView'

export default function BusinessApp({ user, onLogout }: { user: User; onLogout: () => void }) {
  const { lang, formatCurrency } = useLanguage()
  const hub = useStorageHub()
  const nav = [
    { id: 'facilities', label: lang === 'vi' ? 'Tổng quan cơ sở' : 'Facilities overview', icon: Icon.building, group: lang === 'vi' ? 'Danh mục' : 'Portfolio' },
    { id: 'performance', label: lang === 'vi' ? 'Hiệu suất vận hành' : 'Operational performance', icon: Icon.chart, group: lang === 'vi' ? 'Danh mục' : 'Portfolio' },
    { id: 'policies', label: lang === 'vi' ? 'Chính sách thuê' : 'Rental policies', icon: Icon.policy, group: lang === 'vi' ? 'Thương mại' : 'Commercial' },
    { id: 'revenue', label: lang === 'vi' ? 'Báo cáo doanh thu' : 'Revenue report', icon: Icon.dollar, group: lang === 'vi' ? 'Báo cáo' : 'Reporting' },
  ]
  const [page, setPage] = useState(() => getInitialPage(nav, 'facilities'))
  const paidRevenue = hub.payments.filter(item => item.status === 'PAID' && item.type !== 'REFUND').reduce((sum, item) => sum + item.amount, 0)
  const refunds = hub.payments.filter(item => item.status === 'PAID' && item.type === 'REFUND').reduce((sum, item) => sum + item.amount, 0)

  return <Layout user={user} navItems={nav} currentPage={page} onNavigate={setPage} onLogout={onLogout} roleLabel={lang === 'vi' ? 'Giám Đốc Kinh Doanh' : 'Business Manager'} roleColor="bg-amber-100 text-amber-700">
    {page === 'facilities' && <div className="fade-in space-y-5"><SectionHeader title={lang === 'vi' ? 'Tổng Quan Cơ Sở' : 'Facilities Overview'} subtitle={lang === 'vi' ? 'Số liệu được tính trực tiếp từ dữ liệu vận hành dùng chung.' : 'Metrics are calculated directly from shared operational data.'} /><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard title={lang === 'vi' ? 'Cơ sở' : 'Facilities'} value={hub.facilities.length} icon={Icon.building} /><StatCard title={lang === 'vi' ? 'Gian kho' : 'Units'} value={hub.units.length} icon={Icon.box} /><StatCard title={lang === 'vi' ? 'Đang thuê' : 'Active rentals'} value={hub.rentals.filter(item => item.status === 'active').length} icon={Icon.policy} /><StatCard title={lang === 'vi' ? 'Doanh thu đã thu' : 'Collected revenue'} value={formatCurrency(paidRevenue)} icon={Icon.dollar} /></div><div className="grid gap-4 lg:grid-cols-2">{hub.facilities.map(facility => { const units = hub.units.filter(item => item.facilityId === facility.id); const occupied = units.filter(item => item.status === 'occupied').length; return <Card key={facility.id} className="p-5"><div className="flex items-start justify-between"><div><h2 className="font-bold text-stone-900">{facility.name}</h2><p className="mt-1 text-sm text-stone-500">{facility.address}</p></div><Badge variant="success">Active</Badge></div><div className="mt-4"><div className="mb-1 flex justify-between text-xs"><span>{lang === 'vi' ? 'Tỷ lệ lấp đầy' : 'Occupancy'}</span><b>{occupied}/{units.length}</b></div><ProgressBar value={occupied} max={Math.max(1, units.length)} /></div></Card> })}</div></div>}
    {page === 'performance' && <div className="fade-in space-y-5"><SectionHeader title={lang === 'vi' ? 'Hiệu Suất Vận Hành' : 'Operational Performance'} subtitle={lang === 'vi' ? 'Không sử dụng số liệu biểu đồ giả.' : 'No hard-coded chart data is used.'} /><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard title={lang === 'vi' ? 'Đơn chờ duyệt' : 'Awaiting review'} value={hub.holds.filter(item => item.status === 'awaiting_review').length} icon={Icon.calendar} /><StatCard title={lang === 'vi' ? 'Đơn đã cọc' : 'Deposits paid'} value={hub.holds.filter(item => ['DEPOSIT_PAID', 'UNIT_RESERVED', 'READY_FOR_CHECKIN'].includes(item.status)).length} icon={Icon.check} /><StatCard title={lang === 'vi' ? 'Check-in hoàn tất' : 'Completed check-ins'} value={hub.checkins.filter(item => item.status === 'completed').length} icon={Icon.truck} /><StatCard title={lang === 'vi' ? 'Trả kho đang xử lý' : 'Returns in progress'} value={hub.returns.filter(item => item.status !== 'completed').length} icon={Icon.clipboard} /></div></div>}
    {page === 'policies' && <div className="fade-in space-y-5"><SectionHeader title={lang === 'vi' ? 'Chính Sách Thuê Đang Áp Dụng' : 'Active Rental Policies'} subtitle={lang === 'vi' ? 'Cấu hình hiện hành từ StorageHubContext; trang này chỉ đọc.' : 'Current StorageHubContext configuration; this page is read-only.'} /><Card className="p-5"><dl className="grid gap-4 sm:grid-cols-2"><div><dt className="text-xs text-stone-500">{lang === 'vi' ? 'Tỷ lệ cọc giữ chỗ' : 'Booking deposit ratio'}</dt><dd className="mt-1 text-xl font-bold">{hub.config.defaultDepositRatio * 100}%</dd></div><div><dt className="text-xs text-stone-500">{lang === 'vi' ? 'Thời hạn thanh toán' : 'Payment window'}</dt><dd className="mt-1 text-xl font-bold">{hub.config.holdExpiryHours}h</dd></div><div><dt className="text-xs text-stone-500">{lang === 'vi' ? 'Phí trễ' : 'Late fee'}</dt><dd className="mt-1 text-xl font-bold">{formatCurrency(hub.config.lateFeeAmount)}</dd></div><div><dt className="text-xs text-stone-500">DIM divisor</dt><dd className="mt-1 text-xl font-bold">{hub.config.dimDivisor}</dd></div></dl></Card></div>}
    {page === 'revenue' && <div className="fade-in space-y-5"><SectionHeader title={lang === 'vi' ? 'Báo Cáo Doanh Thu' : 'Revenue Report'} subtitle={lang === 'vi' ? 'Giao dịch thật trong state dùng chung.' : 'Actual transactions from shared state.'} /><div className="grid grid-cols-2 gap-3"><StatCard title={lang === 'vi' ? 'Đã thu' : 'Collected'} value={formatCurrency(paidRevenue)} icon={Icon.dollar} /><StatCard title={lang === 'vi' ? 'Đã hoàn' : 'Refunded'} value={formatCurrency(refunds)} icon={Icon.refresh} /></div><Card><Table><Thead><tr><Th>{lang === 'vi' ? 'Giao dịch' : 'Transaction'}</Th><Th>{lang === 'vi' ? 'Loại' : 'Type'}</Th><Th>Status</Th><Th className="text-right">{lang === 'vi' ? 'Số tiền' : 'Amount'}</Th></tr></Thead><Tbody>{hub.payments.map(item => <Tr key={item.id}><Td className="font-mono">{item.id}</Td><Td>{item.type.replace(/_/g, ' ')}</Td><Td><Badge variant={item.status === 'PAID' ? 'success' : 'warning'}>{item.status}</Badge></Td><Td className="text-right font-bold">{formatCurrency(item.amount)}</Td></Tr>)}</Tbody></Table>{!hub.payments.length && <div className="p-10 text-center text-sm text-stone-500">{lang === 'vi' ? 'Chưa có giao dịch.' : 'No transactions yet.'}</div>}</Card></div>}
    {page === 'profile' && <ProfileView user={user} />}
  </Layout>
}
